### ISSUE TITLE
Array input 

### ISSUE THREAD

**Issue by Holmux** [CoRescue/AAUPandemicVentilator_Software#1]
Just looking true the PLC code and found a small bug in the measArrays routine

The code in line 33 is overwriting the value, that was inserted in line 32
![measArrays](https://user-images.githubusercontent.com/63459559/79006567-b6f47000-7b59-11ea-9d3a-88bf5b2c8a8d.png)

**Comment by krhe** [comment]
Thank you for finding the bug. 

The bug is in an untested and until now unused part of the code, because it is related to the flow sensor that has been unavailable until now. Please see https://github.com/CoRescue/AAUPandemicVentilator/blob/master/DMR/Introduction%20to%20documentation%20-%20hardware%20sketch.pdf beta version (Figure 2) of the AAU Pandemic Version. 

We have now received the flow sensor, and are currently testing the code related to it including the code in which you found the bug. These tests and the correction to your bug report will be part of the next release of the AAU Pandemic Ventilator.

**Comment by krhe** [comment]
This as now been fixed and included in the code.
